version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: health-docker-redis

    mysql:
      image: mysql:5.7
      container_name: health-docker-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=funcional
        - MYSQL_DATABASE=deshealth
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=admin
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: health-docker-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: health-docker-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
